/**
 * KaTeX-side fixes + prose fallback token cleanup for sentence-wrapped-as-math path.
 */

/** Fixes inside math strings before KaTeX render. */
export const normalizeCommonLatexTypos = (math) =>
    math
        .replace(/\\begin\{center\}/g, '')
        .replace(/\\end\{center\}/g, '')
        .replace(/\\begin\{tabular\}\{([^}]*)\}/g, (_m, spec) => `\\begin{array}{${String(spec || '').replace(/\|/g, '')}}`)
        .replace(/\\end\{tabular\}/g, '\\end{array}')
        .replace(/\\hline/g, '')
        .replace(/\\\s*(?=(?:\d+\s*&|\\end\{array\}|$))/g, '\\\\ ')
        .replace(/\\text\s*\{\s*((?:(?:\\_)|_){2,})\s*\}/g, '\\underline{\\hspace{3em}}')
        .replace(/\\dot\s*\(\s*([a-zA-Z0-9]+)\s*\)/g, '\\dot{$1}')
        .replace(/\\text\s*\(([^()]+)\)/g, '\\text{$1}')
        .replace(/\\&/g, '&')
        .replace(/\\_/g, '_')

/** Readable prose when inline chunk is misclassified as math. */
export const normalizePlainTextLatexTokens = (value) =>
    value
        .replace(/\\begin\{center\}/g, '')
        .replace(/\\end\{center\}/g, '')
        .replace(/\\begin\{tabular\}\{[^}]*\}/g, '\n')
        .replace(/\\end\{tabular\}/g, '\n')
        .replace(/\\hline/g, '\n')
        .replace(/\\&/g, ' & ')
        .replace(/\\\s*(?=(?:\d+\s*&|[A-Za-z].*&|$))/g, '\n')
        .replace(/\basu=/g, 'as u =')
        .replace(/\bwheree_/g, 'where e_')
        .replace(/([A-Za-z0-9])=([A-Za-z0-9])/g, '$1 = $2')
        .replace(/([A-Za-z0-9])([−-])([A-Za-z0-9])/g, '$1 $2 $3')
        .replace(/([A-Za-z])([α-ωΑ-Ω])/g, '$1 $2')
        .replace(/([α-ωΑ-Ω])([A-Za-z])/g, '$1 $2')
        .replace(/\be_x\b/g, 'eₓ')
        .replace(/\be_y\b/g, 'eᵧ')
        .replace(/\bomega\b/gi, 'ω')
        .replace(/\bdel\b/gi, '∇')
        .replace(/\bv_theta\b/gi, 'v_θ')
        .replace(/\bGamma\b/g, 'Γ')
        .replace(/\bpi\b/g, 'π')
        .replace(/\bpsi\b/gi, 'ψ')
        .replace(/\\text\s*\{\s*((?:(?:\\_)|_){2,})\s*\}/g, '________')
        .replace(/\\text\s*\{([^{}]*)\}/g, '$1')
        .replace(/\\frac\s*\{([^{}]+)\}\s*\{([^{}]+)\}/g, '($1)/($2)')
        .replace(/\\dfrac\s*\{([^{}]+)\}\s*\{([^{}]+)\}/g, '($1)/($2)')
        .replace(/\\tfrac\s*\{([^{}]+)\}\s*\{([^{}]+)\}/g, '($1)/($2)')
        .replace(/\\ldots/g, '…')
        .replace(/\\times/g, '×')
        .replace(/\\cdot/g, '·')
        .replace(/\\leq/g, '≤')
        .replace(/\\geq/g, '≥')
        .replace(/\\neq/g, '≠')
        .replace(/\\lambda/g, 'λ')
        .replace(/\\mu/g, 'μ')
        .replace(/\\theta/g, 'θ')
        .replace(/\\omega/g, 'ω')
        .replace(/\\alpha/g, 'α')
        .replace(/\\beta/g, 'β')
        .replace(/\\gamma/g, 'γ')
        .replace(/\\delta/g, 'δ')
        .replace(/\\bar\{([A-Za-zα-ωΑ-Ω])\}/g, '$1̄')
        .replace(/\\pi/g, 'π')
        .replace(/\bpi\s*\/\s*(\d+)\b/g, 'π/$1')
        .replace(/\\_/g, '_')
